### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by warblo001**
Mint Clone Page ready for code review and approval.

### CODE REVIEW

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
## Hello @warblo001 and @Igors78 

### Congrats on completing your second project 🌟

Add a more descriptive pull request mentioning what you were able to do in this project [check this guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). The title should reflect the feature you added.

This Code Review Request will be marked as invalid on your Dashboard, so please submit a new one once you are ready!


(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Comment by warblo001** [comment]
Displaying and Inputting Data.

In this project, we cloned the Mint Sign Up form as a part of Microverse program.

1.- Created Linters folders as part of Microverse requirements
2.- Created index.html 
3.- Changed folder for index.html
4.- Created the logo image by cutting it from the source page
5.- Created the index file structure
6.- Page structured and reset style added
7.- Updated Readme with new links as Microverse requested
8.- Merged branch 'Feature-Branch' of https://github.com/warblo001/MintClone
9.- Added style to header
10.- Fixed password area 
11.- Updated style.scss 
12.- Styled form footer
13.- Further footer style, button fixed to the bottom and styled
14.- Fixed validation issues
15.- Fixed Readme file
16.- Updates on  README.md
17.- Put css in test
18.- Code formatted for styling errors (linter test failing)
19.- Fixed testing to scss
20.- Change of formatter to Prettier formatter
21.- Readme changed, source page link corrected, code formatted

**Comment by warblo001** [comment]
Displaying and Inputting Data.

In this project, we cloned the Mint Sign Up form as a part of Microverse program.

1.- Created Linters folders as part of Microverse requirements
2.- Created index.html
3.- Changed folder for index.html
4.- Created the logo image by cutting it from the source page
5.- Created the index file structure
6.- Page structured and reset style added
7.- Updated Readme with new links as Microverse requested
8.- Merged branch 'Feature-Branch' of https://github.com/warblo001/MintClone
9.- Added style to header
10.- Fixed password area
11.- Updated style.scss
12.- Styled form footer
13.- Further footer style, button fixed to the bottom and styled
14.- Fixed validation issues
15.- Fixed Readme file
16.- Updates on README.md
17.- Put css in test
18.- Code formatted for styling errors (linter test failing)
19.- Fixed testing to scss
20.- Change of formatter to Prettier formatter
21.- Readme changed, source page link corrected, code formatted

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Igors78 AND @warblo001 
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly work on the suggested changes 👇.

- [ ] The products row is under the Intuit logo and above the form ([link to page](https://accounts.intuit.com/signup.html))
 - [ ] It shows the Mint logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))

- [ ] It shows the Quickbooks logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))

- [ ] It shows the Turbotax logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by warblo001** [comment]
Status: REQUIRED CHANGES ⚠️ 🚧

For this project, we have to make sure nothing is messed up. Kindly work on the suggested changes 👇.

 We have made the products row to be under the Intuit logo and above the form.

 We have made the Mint logo and text (logo on the left, text on the right).

 We have made the Quickbooks logo and text (logo on the left, text on the right).

 We have made Turbotax logo and text (logo on the left, text on the right).

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
### The [clone](https://warblo001.github.io/MintClone/) shows a good understanding and usage of Forms. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
- The project has a descriptive README.md and is professionally done. Good job with that.
- Pull Request has a meaningful title and a short description.
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The markup as well has no errors nor warnings to show. Good job with that.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @Igors78 AND @warblo001! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know on slack at any time. I will be happy to help.**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
